#%RAML 1.0 Trait

uses:
  libraryDataTypes: ../libraries/libraries.raml

responses:
  200:
    description: Updated
    headers:
      content-type:
        description: Updated
    body:
      application/json:
        type: libraryDataTypes.generalRes
        example: !include ../examples/response-200-updated.json