#%RAML 1.0 Trait

headers:
  client_id:
    type: string
    description: The Client-ID of the Application. Will be provided by the Portal
    example: c6VwL5qIGQAhJfmZADoR
  client_secret:
    type: string
    description: The Client-Secret of Application. Will be provided by the Portal
    example: dGfk4xKTGPcZ4MvMxpl5
